# Generated by Django 3.2.9 on 2021-11-26 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20211124_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='descrption',
            new_name='description',
        ),
    ]
