# Generated by Django 3.2.9 on 2021-11-26 08:33

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20211126_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('title',), unique=True, verbose_name='slug'),
        ),
    ]
