# Generated by Django 3.2.10 on 2021-12-10 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_remove_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.faculty', verbose_name='Faculty'),
        ),
    ]
