# Generated by Django 3.2.10 on 2021-12-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_auto_20211210_0008'),
        ('exchange', '0008_question_slug'),
    ]

    operations = [
    ]
