# Generated by Django 3.2.10 on 2021-12-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_merge_0008_auto_20211210_0008_0008_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_title',
            field=models.TextField(default='Title', max_length=256),
        ),
    ]
