# Generated by Django 3.2.10 on 2021-12-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_auto_20211212_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='answervotes',
            name='is_upvote',
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
