# Generated by Django 3.2.10 on 2021-12-12 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_answervotes_is_upvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionVotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_upvote', models.BooleanField(blank=True, default=None)),
                ('question_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='exchange.question')),
                ('user_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
