# Generated by Django 3.2.10 on 2021-12-12 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_questionvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='voted',
            field=models.ManyToManyField(blank=True, default=None, related_name='question_voted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='voted',
            field=models.ManyToManyField(blank=True, default=None, related_name='answer_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
