# Generated by Django 3.2.10 on 2021-12-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_notification_notification_type'),
        ('exchange', '0015_auto_20211212_2254'),
    ]

    operations = [
    ]
