# Generated by Django 3.2.10 on 2021-12-13 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_notification_notification_title'),
        ('exchange', '0015_auto_20211212_2254'),
    ]

    operations = [
    ]
