# Generated by Django 3.2.10 on 2021-12-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0016_merge_20211213_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='', max_length=256),
        ),
    ]
