# Generated by Django 3.2.10 on 2021-12-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0016_merge_20211213_1909'),
        ('exchange', '0017_alter_notification_notification_type'),
    ]

    operations = [
    ]
